import numpy as np


#TODO
class Metric:
    def __init__(self, name: str) -> None: ...
    def reset(self) -> None: ...
    def update(self, y_pred: np.array, y_true: np.array) -> None: ...
    def compute(self) -> float: ...

class Accuracy(Metric): ...
class MSE(Metric): ...
class MAE(Metric): ...

