import numpy as np


#TODO
class OutputHead:
    def __init__(self, from_logits: bool = True, name: str | None = None) -> None: ...

    def forward(self, logits: np.array) -> np.array: ...
    def backward(self, grad_out: np.array) -> np.array: ...


class IdentityHead(OutputHead):
    def forward(self, logits: np.array) -> np.array: ...
    def backward(self, grad_out: np.array) -> np.array: ...

class SigmoidHead(OutputHead):
    def forward(self, logits: np.array) -> np.array: ...
    def backward(self, grad_out: np.array) -> np.array: ...

class SoftmaxHead(OutputHead):
    def __init__(self, dim: int = -1, from_logits: bool = True, name: str | None = None) -> None: ...
    def forward(self, logits: np.array) -> np.array: ...
    def backward(self, grad_out: np.array) -> np.array: ...



